// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvGaNNhCwMEk4RlFioSO-ZpwN3CKtX42Q',
    appId: '1:374712297663:web:5e1aa9f02879c6eaa17e0a',
    messagingSenderId: '374712297663',
    projectId: 'my-app-fashion',
    authDomain: 'my-app-fashion.firebaseapp.com',
    storageBucket: 'my-app-fashion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXmqs87cICQLf2E-Tkf2vBi5y8yZsFEI',
    appId: '1:374712297663:android:d555a47e6e633b1fa17e0a',
    messagingSenderId: '374712297663',
    projectId: 'my-app-fashion',
    storageBucket: 'my-app-fashion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1h6UQWpt0oSlu8kkcc4fseyDEbQ_qag',
    appId: '1:374712297663:ios:ef522d376b9553a8a17e0a',
    messagingSenderId: '374712297663',
    projectId: 'my-app-fashion',
    storageBucket: 'my-app-fashion.appspot.com',
    iosBundleId: 'com.example.fashion3x',
  );

}